// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import { combineImportEntries, defaultImportEntries } from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { useState, useRef, forwardRef, useEffect } from 'react';
import React from 'react';
import * as React_7214d18997ee864dd178de7b3a8430f6783e8b89 from 'react';
import { Link, Text, AppPlaceholder, RichText, NextImage, useSitecore, Image as Image_8a80e63291fea86e0744df19113dc44bec187216, CdpHelper, withDatasourceCheck } from '@sitecore-content-sdk/nextjs';
import componentMap from '.sitecore/component-map';
import { File, FileText, Image, X, CircleCheckIcon, InfoIcon, Loader2Icon, OctagonXIcon, TriangleAlertIcon, XIcon, CheckIcon, ChevronDownIcon, ChevronUpIcon, CircleIcon, ChevronRightIcon, ChevronLeft, ChevronRight, CircleHelp, Upload, CheckCircle2, HelpCircle, Info, ArrowRight, ChevronDown, ChevronUp, Building2, User, CreditCard, Mail, Phone, Home, FileCheck, Clock, Menu, Check, Save } from 'lucide-react';
import * as LucideIcons from 'lucide-react';
import { toast, Toaster } from 'sonner';
import { Button } from 'components/da-loan/ui-premetive/button';
import { Card, CardContent } from 'components/da-loan/ui-premetive/card';
import { Progress } from 'components/da-loan/ui-premetive/progress';
import * as TooltipPrimitive from '@radix-ui/react-tooltip';
import { cn } from 'lib/utils';
import { useTheme } from 'next-themes';
import * as SliderPrimitive from '@radix-ui/react-slider';
import * as SheetPrimitive from '@radix-ui/react-dialog';
import * as SelectPrimitive from '@radix-ui/react-select';
import * as ScrollAreaPrimitive from '@radix-ui/react-scroll-area';
import * as RadioGroupPrimitive from '@radix-ui/react-radio-group';
import * as ProgressPrimitive from '@radix-ui/react-progress';
import * as LabelPrimitive from '@radix-ui/react-label';
import * as DropdownMenuPrimitive from '@radix-ui/react-dropdown-menu';
import * as CheckboxPrimitive from '@radix-ui/react-checkbox';
import useEmblaCarousel from 'embla-carousel-react';
import { Slot } from '@radix-ui/react-slot';
import { cva } from 'class-variance-authority';
import { Slider } from 'components/da-loan/ui-premetive/slider';
import { Label } from 'components/da-loan/ui-premetive/label';
import { RadioGroup, RadioGroupItem } from 'components/da-loan/ui-premetive/radio-group';
import { FileUploadInput } from 'components/da-loan/ui/file-upload-input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from 'components/da-loan/ui/select';
import { Tooltip, TooltipContent, TooltipTrigger } from 'src/components/da-loan/ui-premetive/tooltip';
import { useRouter } from 'next/navigation';
import { ScrollArea } from 'components/da-loan/ui-premetive/scroll-area';
import { Checkbox } from 'components/da-loan/ui-premetive/checkbox';
import { Controller, useForm, useWatch } from 'react-hook-form';
import { DropDownList } from 'components/da-loan/ui/drop-down-list';
import { StandardNumberInput } from 'components/da-loan/ui/standard-number-input';
import { useJsApiLoader } from '@react-google-maps/api';
import { StandardTextInput } from 'components/da-loan/ui/standard-text-input';
import { Timer } from 'components/da-loan/ui-premetive/timer';
import { StandardNumberInput as StandardNumberInput_f828539b62090e97a5826753effd80596838b726 } from 'src/components/da-loan/ui/standard-number-input';
import Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 from 'next/link';
import reviewData from 'lib/review.json';
import { Checkbox as Checkbox_2412d64d47050439b4c8c828d8666fb90e2da941 } from 'src/components/da-loan/ui-premetive/checkbox';
import { Label as Label_65505704d617a7c76aeb19308ba7b751ba95b874 } from 'src/components/da-loan/ui-premetive/label';
import { RadioGroupWithIcon } from 'components/da-loan/ui/radio-group-with-icon';
import { RadioGroup as RadioGroup_fe7f30ab2ac350afceb40375b326155b191dbbb4 } from 'components/da-loan/ui/radio-group-input';
import { IdentityDocument } from 'components/da-loan/ui/identity-document';
import { Alert } from 'src/components/da-loan/ui/alert';
import { RangeSlider } from 'components/da-loan/ui/range-slider';
import { IncomeInput } from 'src/components/da-loan/ui/income-input';
import Image_5d8ce56058442d94361877e28c501c951a554a6a from 'next/image';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger, SheetClose } from 'components/da-loan/ui-premetive/sheet';
import { Logo } from 'components/da-loan/ui-premetive/logo';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from 'components/da-loan/ui-premetive/dropdown-menu';
import { Carousel, CarouselContent, CarouselItem, CarouselPagination } from 'components/da-loan/ui-premetive/carousel';
import Autoplay from 'embla-carousel-autoplay';
import { DesktopNavigation, MobileMenuButton } from 'components/da-loan/layout/navigation-menu/navigation-menu';
import client from 'src/lib/sitecore-client';
import { pageView } from '@sitecore-cloudsdk/events/browser';
import config from 'sitecore.config';

const importMap = [
  {
    module: 'react',
    exports: [
      { name: 'useState', value: useState },
      { name: 'useRef', value: useRef },
      { name: 'forwardRef', value: forwardRef },
      { name: 'useEffect', value: useEffect },
      { name: 'default', value: React },
      { name: '*', value: React_7214d18997ee864dd178de7b3a8430f6783e8b89 },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Link', value: Link },
      { name: 'Text', value: Text },
      { name: 'AppPlaceholder', value: AppPlaceholder },
      { name: 'RichText', value: RichText },
      { name: 'NextImage', value: NextImage },
      { name: 'useSitecore', value: useSitecore },
      { name: 'Image', value: Image_8a80e63291fea86e0744df19113dc44bec187216 },
      { name: 'CdpHelper', value: CdpHelper },
      { name: 'withDatasourceCheck', value: withDatasourceCheck },
    ]
  },
  {
    module: '.sitecore/component-map',
    exports: [
      { name: 'default', value: componentMap },
    ]
  },
  {
    module: 'lucide-react',
    exports: [
      { name: 'File', value: File },
      { name: 'FileText', value: FileText },
      { name: 'Image', value: Image },
      { name: 'X', value: X },
      { name: 'CircleCheckIcon', value: CircleCheckIcon },
      { name: 'InfoIcon', value: InfoIcon },
      { name: 'Loader2Icon', value: Loader2Icon },
      { name: 'OctagonXIcon', value: OctagonXIcon },
      { name: 'TriangleAlertIcon', value: TriangleAlertIcon },
      { name: 'XIcon', value: XIcon },
      { name: 'CheckIcon', value: CheckIcon },
      { name: 'ChevronDownIcon', value: ChevronDownIcon },
      { name: 'ChevronUpIcon', value: ChevronUpIcon },
      { name: 'CircleIcon', value: CircleIcon },
      { name: 'ChevronRightIcon', value: ChevronRightIcon },
      { name: 'ChevronLeft', value: ChevronLeft },
      { name: 'ChevronRight', value: ChevronRight },
      { name: 'CircleHelp', value: CircleHelp },
      { name: 'Upload', value: Upload },
      { name: 'CheckCircle2', value: CheckCircle2 },
      { name: 'HelpCircle', value: HelpCircle },
      { name: 'Info', value: Info },
      { name: 'ArrowRight', value: ArrowRight },
      { name: 'ChevronDown', value: ChevronDown },
      { name: 'ChevronUp', value: ChevronUp },
      { name: 'Building2', value: Building2 },
      { name: 'User', value: User },
      { name: 'CreditCard', value: CreditCard },
      { name: 'Mail', value: Mail },
      { name: 'Phone', value: Phone },
      { name: 'Home', value: Home },
      { name: 'FileCheck', value: FileCheck },
      { name: 'Clock', value: Clock },
      { name: 'Menu', value: Menu },
      { name: 'Check', value: Check },
      { name: 'Save', value: Save },
      { name: '*', value: LucideIcons },
    ]
  },
  {
    module: 'sonner',
    exports: [
      { name: 'toast', value: toast },
      { name: 'Toaster', value: Toaster },
    ]
  },
  {
    module: 'components/da-loan/ui-premetive/button',
    exports: [
      { name: 'Button', value: Button },
    ]
  },
  {
    module: 'components/da-loan/ui-premetive/card',
    exports: [
      { name: 'Card', value: Card },
      { name: 'CardContent', value: CardContent },
    ]
  },
  {
    module: 'components/da-loan/ui-premetive/progress',
    exports: [
      { name: 'Progress', value: Progress },
    ]
  },
  {
    module: '@radix-ui/react-tooltip',
    exports: [
      { name: '*', value: TooltipPrimitive },
    ]
  },
  {
    module: 'lib/utils',
    exports: [
      { name: 'cn', value: cn },
    ]
  },
  {
    module: 'next-themes',
    exports: [
      { name: 'useTheme', value: useTheme },
    ]
  },
  {
    module: '@radix-ui/react-slider',
    exports: [
      { name: '*', value: SliderPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-dialog',
    exports: [
      { name: '*', value: SheetPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-select',
    exports: [
      { name: '*', value: SelectPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-scroll-area',
    exports: [
      { name: '*', value: ScrollAreaPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-radio-group',
    exports: [
      { name: '*', value: RadioGroupPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-progress',
    exports: [
      { name: '*', value: ProgressPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-label',
    exports: [
      { name: '*', value: LabelPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-dropdown-menu',
    exports: [
      { name: '*', value: DropdownMenuPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-checkbox',
    exports: [
      { name: '*', value: CheckboxPrimitive },
    ]
  },
  {
    module: 'embla-carousel-react',
    exports: [
      { name: 'default', value: useEmblaCarousel },
    ]
  },
  {
    module: '@radix-ui/react-slot',
    exports: [
      { name: 'Slot', value: Slot },
    ]
  },
  {
    module: 'class-variance-authority',
    exports: [
      { name: 'cva', value: cva },
    ]
  },
  {
    module: 'components/da-loan/ui-premetive/slider',
    exports: [
      { name: 'Slider', value: Slider },
    ]
  },
  {
    module: 'components/da-loan/ui-premetive/label',
    exports: [
      { name: 'Label', value: Label },
    ]
  },
  {
    module: 'components/da-loan/ui-premetive/radio-group',
    exports: [
      { name: 'RadioGroup', value: RadioGroup },
      { name: 'RadioGroupItem', value: RadioGroupItem },
    ]
  },
  {
    module: 'components/da-loan/ui/file-upload-input',
    exports: [
      { name: 'FileUploadInput', value: FileUploadInput },
    ]
  },
  {
    module: 'src/components/da-loan/ui-premetive/select',
    exports: [
      { name: 'Select', value: Select },
      { name: 'SelectContent', value: SelectContent },
      { name: 'SelectItem', value: SelectItem },
      { name: 'SelectTrigger', value: SelectTrigger },
      { name: 'SelectValue', value: SelectValue },
    ]
  },
  {
    module: 'src/components/da-loan/ui-premetive/tooltip',
    exports: [
      { name: 'Tooltip', value: Tooltip },
      { name: 'TooltipContent', value: TooltipContent },
      { name: 'TooltipTrigger', value: TooltipTrigger },
    ]
  },
  {
    module: 'next/navigation',
    exports: [
      { name: 'useRouter', value: useRouter },
    ]
  },
  {
    module: 'components/da-loan/ui-premetive/scroll-area',
    exports: [
      { name: 'ScrollArea', value: ScrollArea },
    ]
  },
  {
    module: 'components/da-loan/ui-premetive/checkbox',
    exports: [
      { name: 'Checkbox', value: Checkbox },
    ]
  },
  {
    module: 'react-hook-form',
    exports: [
      { name: 'Controller', value: Controller },
      { name: 'useForm', value: useForm },
      { name: 'useWatch', value: useWatch },
    ]
  },
  {
    module: 'components/da-loan/ui/drop-down-list',
    exports: [
      { name: 'DropDownList', value: DropDownList },
    ]
  },
  {
    module: 'components/da-loan/ui/standard-number-input',
    exports: [
      { name: 'StandardNumberInput', value: StandardNumberInput },
    ]
  },
  {
    module: '@react-google-maps/api',
    exports: [
      { name: 'useJsApiLoader', value: useJsApiLoader },
    ]
  },
  {
    module: 'components/da-loan/ui/standard-text-input',
    exports: [
      { name: 'StandardTextInput', value: StandardTextInput },
    ]
  },
  {
    module: 'components/da-loan/ui-premetive/timer',
    exports: [
      { name: 'Timer', value: Timer },
    ]
  },
  {
    module: 'src/components/da-loan/ui/standard-number-input',
    exports: [
      { name: 'StandardNumberInput', value: StandardNumberInput_f828539b62090e97a5826753effd80596838b726 },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 },
    ]
  },
  {
    module: 'lib/review.json',
    exports: [
      { name: 'default', value: reviewData },
    ]
  },
  {
    module: 'src/components/da-loan/ui-premetive/checkbox',
    exports: [
      { name: 'Checkbox', value: Checkbox_2412d64d47050439b4c8c828d8666fb90e2da941 },
    ]
  },
  {
    module: 'src/components/da-loan/ui-premetive/label',
    exports: [
      { name: 'Label', value: Label_65505704d617a7c76aeb19308ba7b751ba95b874 },
    ]
  },
  {
    module: 'components/da-loan/ui/radio-group-with-icon',
    exports: [
      { name: 'RadioGroupWithIcon', value: RadioGroupWithIcon },
    ]
  },
  {
    module: 'components/da-loan/ui/radio-group-input',
    exports: [
      { name: 'RadioGroup', value: RadioGroup_fe7f30ab2ac350afceb40375b326155b191dbbb4 },
    ]
  },
  {
    module: 'components/da-loan/ui/identity-document',
    exports: [
      { name: 'IdentityDocument', value: IdentityDocument },
    ]
  },
  {
    module: 'src/components/da-loan/ui/alert',
    exports: [
      { name: 'Alert', value: Alert },
    ]
  },
  {
    module: 'components/da-loan/ui/range-slider',
    exports: [
      { name: 'RangeSlider', value: RangeSlider },
    ]
  },
  {
    module: 'src/components/da-loan/ui/income-input',
    exports: [
      { name: 'IncomeInput', value: IncomeInput },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image_5d8ce56058442d94361877e28c501c951a554a6a },
    ]
  },
  {
    module: 'components/da-loan/ui-premetive/sheet',
    exports: [
      { name: 'Sheet', value: Sheet },
      { name: 'SheetContent', value: SheetContent },
      { name: 'SheetHeader', value: SheetHeader },
      { name: 'SheetTitle', value: SheetTitle },
      { name: 'SheetTrigger', value: SheetTrigger },
      { name: 'SheetClose', value: SheetClose },
    ]
  },
  {
    module: 'components/da-loan/ui-premetive/logo',
    exports: [
      { name: 'Logo', value: Logo },
    ]
  },
  {
    module: 'components/da-loan/ui-premetive/dropdown-menu',
    exports: [
      { name: 'DropdownMenu', value: DropdownMenu },
      { name: 'DropdownMenuContent', value: DropdownMenuContent },
      { name: 'DropdownMenuItem', value: DropdownMenuItem },
      { name: 'DropdownMenuTrigger', value: DropdownMenuTrigger },
    ]
  },
  {
    module: 'components/da-loan/ui-premetive/carousel',
    exports: [
      { name: 'Carousel', value: Carousel },
      { name: 'CarouselContent', value: CarouselContent },
      { name: 'CarouselItem', value: CarouselItem },
      { name: 'CarouselPagination', value: CarouselPagination },
    ]
  },
  {
    module: 'embla-carousel-autoplay',
    exports: [
      { name: 'default', value: Autoplay },
    ]
  },
  {
    module: 'components/da-loan/layout/navigation-menu/navigation-menu',
    exports: [
      { name: 'DesktopNavigation', value: DesktopNavigation },
      { name: 'MobileMenuButton', value: MobileMenuButton },
    ]
  },
  {
    module: 'src/lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: '@sitecore-cloudsdk/events/browser',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  }
];

export default combineImportEntries(defaultImportEntries, importMap);
