// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import { combineImportEntries, defaultImportEntries } from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { useState, useRef, useEffect, forwardRef, useCallback } from 'react';
import React from 'react';
import * as React_7214d18997ee864dd178de7b3a8430f6783e8b89 from 'react';
import { Link, Text, AppPlaceholder, RichText, NextImage, useSitecore, CdpHelper, withDatasourceCheck } from '@sitecore-content-sdk/nextjs';
import componentMap from '.sitecore/component-map';
import { File, FileText, Image, X, CircleCheckIcon, InfoIcon, Loader2Icon, OctagonXIcon, TriangleAlertIcon, XIcon, CircleIcon, Dot, CheckIcon, ChevronRightIcon, ChevronLeft, ChevronRight, CircleHelp, ChevronDownIcon, ChevronUpIcon, Upload, CheckCircle2, HelpCircle, Info, ArrowRight, ChevronDown, ChevronUp, Building2, User, CreditCard, Mail, Phone, Home, FileCheck, Clock, Menu, Check, Save, Star, Heart, UploadCloud, Wallet, Calendar, TrendingDown, Shield } from 'lucide-react';
import * as LucideIcons from 'lucide-react';
import { toast, Toaster } from 'sonner';
import { Button } from 'components/da-loan/ui-primitive/button';
import { Card, CardContent } from 'components/da-loan/ui-primitive/card';
import { Progress } from 'components/da-loan/ui-primitive/progress';
import * as TooltipPrimitive from '@radix-ui/react-tooltip';
import { cn } from 'lib/utils';
import { useTheme } from 'next-themes';
import * as SliderPrimitive from '@radix-ui/react-slider';
import * as SheetPrimitive from '@radix-ui/react-dialog';
import * as ScrollAreaPrimitive from '@radix-ui/react-scroll-area';
import * as RadioGroupPrimitive from '@radix-ui/react-radio-group';
import * as ProgressPrimitive from '@radix-ui/react-progress';
import * as LabelPrimitive from '@radix-ui/react-label';
import { OTPInput, OTPInputContext } from 'input-otp';
import * as DropdownMenuPrimitive from '@radix-ui/react-dropdown-menu';
import * as CheckboxPrimitive from '@radix-ui/react-checkbox';
import useEmblaCarousel from 'embla-carousel-react';
import { Slot } from '@radix-ui/react-slot';
import { cva } from 'class-variance-authority';
import { ScrollArea } from 'components/da-loan/ui-primitive/scroll-area';
import { Checkbox } from 'components/da-loan/ui-primitive/checkbox';
import { Label } from 'components/da-loan/ui-primitive/label';
import * as SelectPrimitive from '@radix-ui/react-select';
import { Slider } from 'components/da-loan/ui-primitive/slider';
import { RadioGroup, RadioGroupItem } from 'components/da-loan/ui-primitive/radio-group';
import { FileUploadInput } from 'components/da-loan/ui/file-upload-input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from 'src/components/da-loan/ui/select';
import { Tooltip, TooltipContent, TooltipTrigger } from 'src/components/da-loan/ui-primitive/tooltip';
import { useRouter, usePathname } from 'next/navigation';
import { Controller, useWatch, useForm } from 'react-hook-form';
import { Input } from 'src/components/da-loan/ui-primitive/input';
import { DropDownList } from 'components/da-loan/ui/drop-down-list';
import { StandardNumberInput } from 'components/da-loan/ui/standard-number-input';
import { useJsApiLoader } from '@react-google-maps/api';
import { StandardTextInput } from 'components/da-loan/ui/standard-text-input';
import { Timer } from 'components/da-loan/ui-primitive/timer';
import { InputOTP, InputOTPGroup, InputOTPSlot } from 'components/da-loan/ui-primitive/input-otp';
import Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 from 'next/link';
import reviewData from 'lib/review.json';
import { Checkbox as Checkbox_2c4d13020f25f489036348d2403a7f26aaedb81d } from 'src/components/da-loan/ui-primitive/checkbox';
import { Label as Label_8ae250ca92c322e6a449d8adec73c03cf6b26442 } from 'src/components/da-loan/ui-primitive/label';
import { RadioGroupWithIcon } from 'components/da-loan/ui/radio-group-with-icon';
import { RadioGroup as RadioGroup_fe7f30ab2ac350afceb40375b326155b191dbbb4 } from 'components/da-loan/ui/radio-group-input';
import { IdentityDocument } from 'components/da-loan/ui/identity-document';
import { StandardNumberInput as StandardNumberInput_f828539b62090e97a5826753effd80596838b726 } from 'src/components/da-loan/ui/standard-number-input';
import { Alert } from 'src/components/da-loan/ui/alert';
import { formatCurrency, formatPercentage } from 'lib/format';
import { RangeSlider } from 'components/da-loan/ui/range-slider';
import { TermsModalInput } from 'components/da-loan/ui/terms-modal-input';
import { SouthAfricanIDInput, validateSouthAfricanID } from 'components/da-loan/ui/south-african-id-input';
import { IncomeInput } from 'components/da-loan/ui/income-input';
import { IncomeInput as IncomeInput_24b3169fe3ee539e8d45512dc2dfe583feecac17 } from 'src/components/da-loan/ui/income-input';
import Image_5d8ce56058442d94361877e28c501c951a554a6a from 'next/image';
import { LoanCalculator } from 'components/da-loan/blocks/loan-calculator';
import { ConsolidationCalculator } from 'components/da-loan/blocks/consolidation-calculator';
import { zodResolver } from '@hookform/resolvers/zod';
import { Input as Input_849d1c78d50a3e8698b64091f7b49054601f2a35 } from 'components/da-loan/ui-primitive/input';
import { pulseRegistrationSchema } from 'lib/schemas';
import { LoanProductsBlock } from 'components/da-loan/blocks/loan-products-block';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger, SheetClose } from 'components/da-loan/ui-primitive/sheet';
import { Logo } from 'components/da-loan/ui-primitive/logo';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from 'components/da-loan/ui-primitive/dropdown-menu';
import { PromoCard } from 'components/da-loan/blocks/promo-card';
import { LoanApplicationFlowAlt } from 'components/da-loan/layout/loan-application-flow-alt/loan-application-flow-alt';
import { Carousel, CarouselContent, CarouselItem, CarouselPagination } from 'components/da-loan/ui-primitive/carousel';
import Autoplay from 'embla-carousel-autoplay';
import { DesktopNavigation, MobileMenuButton } from 'components/da-loan/layout/navigation-menu/navigation-menu';
import { directTalkTopics } from 'src/components/da-loan/layout/direct-talk/topics-data';
import { ConsolidationBenefits } from 'components/da-loan/blocks/consolidation-benefits';
import { FAQAccordion } from 'components/da-loan/blocks/faq-accordion';
import { OfferSlider } from 'components/da-loan/blocks/offer-slider';
import { useIsInView } from 'hooks/use-is-in-view';
import { LoanSlider } from 'src/components/da-loan/blocks/slider-component';
import { LoanSummary } from 'src/components/da-loan/blocks/loan-summary';
import { AccountSelectionForm } from 'src/components/da-loan/blocks/account-selection-form';
import { ConsolidationSummary } from 'src/components/da-loan/blocks/consolidation-summary';
import { Select as Select_87560054f54a6d1e822ff059c9b85315bc1265a4, SelectContent as SelectContent_87560054f54a6d1e822ff059c9b85315bc1265a4, SelectItem as SelectItem_87560054f54a6d1e822ff059c9b85315bc1265a4, SelectTrigger as SelectTrigger_87560054f54a6d1e822ff059c9b85315bc1265a4, SelectValue as SelectValue_87560054f54a6d1e822ff059c9b85315bc1265a4 } from 'components/da-loan/ui/select';
import client from 'src/lib/sitecore-client';
import { pageView } from '@sitecore-cloudsdk/events/browser';
import config from 'sitecore.config';

const importMap = [
  {
    module: 'react',
    exports: [
      { name: 'useState', value: useState },
      { name: 'useRef', value: useRef },
      { name: 'useEffect', value: useEffect },
      { name: 'forwardRef', value: forwardRef },
      { name: 'useCallback', value: useCallback },
      { name: 'default', value: React },
      { name: '*', value: React_7214d18997ee864dd178de7b3a8430f6783e8b89 },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Link', value: Link },
      { name: 'Text', value: Text },
      { name: 'AppPlaceholder', value: AppPlaceholder },
      { name: 'RichText', value: RichText },
      { name: 'NextImage', value: NextImage },
      { name: 'useSitecore', value: useSitecore },
      { name: 'CdpHelper', value: CdpHelper },
      { name: 'withDatasourceCheck', value: withDatasourceCheck },
    ]
  },
  {
    module: '.sitecore/component-map',
    exports: [
      { name: 'default', value: componentMap },
    ]
  },
  {
    module: 'lucide-react',
    exports: [
      { name: 'File', value: File },
      { name: 'FileText', value: FileText },
      { name: 'Image', value: Image },
      { name: 'X', value: X },
      { name: 'CircleCheckIcon', value: CircleCheckIcon },
      { name: 'InfoIcon', value: InfoIcon },
      { name: 'Loader2Icon', value: Loader2Icon },
      { name: 'OctagonXIcon', value: OctagonXIcon },
      { name: 'TriangleAlertIcon', value: TriangleAlertIcon },
      { name: 'XIcon', value: XIcon },
      { name: 'CircleIcon', value: CircleIcon },
      { name: 'Dot', value: Dot },
      { name: 'CheckIcon', value: CheckIcon },
      { name: 'ChevronRightIcon', value: ChevronRightIcon },
      { name: 'ChevronLeft', value: ChevronLeft },
      { name: 'ChevronRight', value: ChevronRight },
      { name: 'CircleHelp', value: CircleHelp },
      { name: 'ChevronDownIcon', value: ChevronDownIcon },
      { name: 'ChevronUpIcon', value: ChevronUpIcon },
      { name: 'Upload', value: Upload },
      { name: 'CheckCircle2', value: CheckCircle2 },
      { name: 'HelpCircle', value: HelpCircle },
      { name: 'Info', value: Info },
      { name: 'ArrowRight', value: ArrowRight },
      { name: 'ChevronDown', value: ChevronDown },
      { name: 'ChevronUp', value: ChevronUp },
      { name: 'Building2', value: Building2 },
      { name: 'User', value: User },
      { name: 'CreditCard', value: CreditCard },
      { name: 'Mail', value: Mail },
      { name: 'Phone', value: Phone },
      { name: 'Home', value: Home },
      { name: 'FileCheck', value: FileCheck },
      { name: 'Clock', value: Clock },
      { name: 'Menu', value: Menu },
      { name: 'Check', value: Check },
      { name: 'Save', value: Save },
      { name: 'Star', value: Star },
      { name: 'Heart', value: Heart },
      { name: 'UploadCloud', value: UploadCloud },
      { name: 'Wallet', value: Wallet },
      { name: 'Calendar', value: Calendar },
      { name: 'TrendingDown', value: TrendingDown },
      { name: 'Shield', value: Shield },
      { name: '*', value: LucideIcons },
    ]
  },
  {
    module: 'sonner',
    exports: [
      { name: 'toast', value: toast },
      { name: 'Toaster', value: Toaster },
    ]
  },
  {
    module: 'components/da-loan/ui-primitive/button',
    exports: [
      { name: 'Button', value: Button },
    ]
  },
  {
    module: 'components/da-loan/ui-primitive/card',
    exports: [
      { name: 'Card', value: Card },
      { name: 'CardContent', value: CardContent },
    ]
  },
  {
    module: 'components/da-loan/ui-primitive/progress',
    exports: [
      { name: 'Progress', value: Progress },
    ]
  },
  {
    module: '@radix-ui/react-tooltip',
    exports: [
      { name: '*', value: TooltipPrimitive },
    ]
  },
  {
    module: 'lib/utils',
    exports: [
      { name: 'cn', value: cn },
    ]
  },
  {
    module: 'next-themes',
    exports: [
      { name: 'useTheme', value: useTheme },
    ]
  },
  {
    module: '@radix-ui/react-slider',
    exports: [
      { name: '*', value: SliderPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-dialog',
    exports: [
      { name: '*', value: SheetPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-scroll-area',
    exports: [
      { name: '*', value: ScrollAreaPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-radio-group',
    exports: [
      { name: '*', value: RadioGroupPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-progress',
    exports: [
      { name: '*', value: ProgressPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-label',
    exports: [
      { name: '*', value: LabelPrimitive },
    ]
  },
  {
    module: 'input-otp',
    exports: [
      { name: 'OTPInput', value: OTPInput },
      { name: 'OTPInputContext', value: OTPInputContext },
    ]
  },
  {
    module: '@radix-ui/react-dropdown-menu',
    exports: [
      { name: '*', value: DropdownMenuPrimitive },
    ]
  },
  {
    module: '@radix-ui/react-checkbox',
    exports: [
      { name: '*', value: CheckboxPrimitive },
    ]
  },
  {
    module: 'embla-carousel-react',
    exports: [
      { name: 'default', value: useEmblaCarousel },
    ]
  },
  {
    module: '@radix-ui/react-slot',
    exports: [
      { name: 'Slot', value: Slot },
    ]
  },
  {
    module: 'class-variance-authority',
    exports: [
      { name: 'cva', value: cva },
    ]
  },
  {
    module: 'components/da-loan/ui-primitive/scroll-area',
    exports: [
      { name: 'ScrollArea', value: ScrollArea },
    ]
  },
  {
    module: 'components/da-loan/ui-primitive/checkbox',
    exports: [
      { name: 'Checkbox', value: Checkbox },
    ]
  },
  {
    module: 'components/da-loan/ui-primitive/label',
    exports: [
      { name: 'Label', value: Label },
    ]
  },
  {
    module: '@radix-ui/react-select',
    exports: [
      { name: '*', value: SelectPrimitive },
    ]
  },
  {
    module: 'components/da-loan/ui-primitive/slider',
    exports: [
      { name: 'Slider', value: Slider },
    ]
  },
  {
    module: 'components/da-loan/ui-primitive/radio-group',
    exports: [
      { name: 'RadioGroup', value: RadioGroup },
      { name: 'RadioGroupItem', value: RadioGroupItem },
    ]
  },
  {
    module: 'components/da-loan/ui/file-upload-input',
    exports: [
      { name: 'FileUploadInput', value: FileUploadInput },
    ]
  },
  {
    module: 'src/components/da-loan/ui/select',
    exports: [
      { name: 'Select', value: Select },
      { name: 'SelectContent', value: SelectContent },
      { name: 'SelectItem', value: SelectItem },
      { name: 'SelectTrigger', value: SelectTrigger },
      { name: 'SelectValue', value: SelectValue },
    ]
  },
  {
    module: 'src/components/da-loan/ui-primitive/tooltip',
    exports: [
      { name: 'Tooltip', value: Tooltip },
      { name: 'TooltipContent', value: TooltipContent },
      { name: 'TooltipTrigger', value: TooltipTrigger },
    ]
  },
  {
    module: 'next/navigation',
    exports: [
      { name: 'useRouter', value: useRouter },
      { name: 'usePathname', value: usePathname },
    ]
  },
  {
    module: 'react-hook-form',
    exports: [
      { name: 'Controller', value: Controller },
      { name: 'useWatch', value: useWatch },
      { name: 'useForm', value: useForm },
    ]
  },
  {
    module: 'src/components/da-loan/ui-primitive/input',
    exports: [
      { name: 'Input', value: Input },
    ]
  },
  {
    module: 'components/da-loan/ui/drop-down-list',
    exports: [
      { name: 'DropDownList', value: DropDownList },
    ]
  },
  {
    module: 'components/da-loan/ui/standard-number-input',
    exports: [
      { name: 'StandardNumberInput', value: StandardNumberInput },
    ]
  },
  {
    module: '@react-google-maps/api',
    exports: [
      { name: 'useJsApiLoader', value: useJsApiLoader },
    ]
  },
  {
    module: 'components/da-loan/ui/standard-text-input',
    exports: [
      { name: 'StandardTextInput', value: StandardTextInput },
    ]
  },
  {
    module: 'components/da-loan/ui-primitive/timer',
    exports: [
      { name: 'Timer', value: Timer },
    ]
  },
  {
    module: 'components/da-loan/ui-primitive/input-otp',
    exports: [
      { name: 'InputOTP', value: InputOTP },
      { name: 'InputOTPGroup', value: InputOTPGroup },
      { name: 'InputOTPSlot', value: InputOTPSlot },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 },
    ]
  },
  {
    module: 'lib/review.json',
    exports: [
      { name: 'default', value: reviewData },
    ]
  },
  {
    module: 'src/components/da-loan/ui-primitive/checkbox',
    exports: [
      { name: 'Checkbox', value: Checkbox_2c4d13020f25f489036348d2403a7f26aaedb81d },
    ]
  },
  {
    module: 'src/components/da-loan/ui-primitive/label',
    exports: [
      { name: 'Label', value: Label_8ae250ca92c322e6a449d8adec73c03cf6b26442 },
    ]
  },
  {
    module: 'components/da-loan/ui/radio-group-with-icon',
    exports: [
      { name: 'RadioGroupWithIcon', value: RadioGroupWithIcon },
    ]
  },
  {
    module: 'components/da-loan/ui/radio-group-input',
    exports: [
      { name: 'RadioGroup', value: RadioGroup_fe7f30ab2ac350afceb40375b326155b191dbbb4 },
    ]
  },
  {
    module: 'components/da-loan/ui/identity-document',
    exports: [
      { name: 'IdentityDocument', value: IdentityDocument },
    ]
  },
  {
    module: 'src/components/da-loan/ui/standard-number-input',
    exports: [
      { name: 'StandardNumberInput', value: StandardNumberInput_f828539b62090e97a5826753effd80596838b726 },
    ]
  },
  {
    module: 'src/components/da-loan/ui/alert',
    exports: [
      { name: 'Alert', value: Alert },
    ]
  },
  {
    module: 'lib/format',
    exports: [
      { name: 'formatCurrency', value: formatCurrency },
      { name: 'formatPercentage', value: formatPercentage },
    ]
  },
  {
    module: 'components/da-loan/ui/range-slider',
    exports: [
      { name: 'RangeSlider', value: RangeSlider },
    ]
  },
  {
    module: 'components/da-loan/ui/terms-modal-input',
    exports: [
      { name: 'TermsModalInput', value: TermsModalInput },
    ]
  },
  {
    module: 'components/da-loan/ui/south-african-id-input',
    exports: [
      { name: 'SouthAfricanIDInput', value: SouthAfricanIDInput },
      { name: 'validateSouthAfricanID', value: validateSouthAfricanID },
    ]
  },
  {
    module: 'components/da-loan/ui/income-input',
    exports: [
      { name: 'IncomeInput', value: IncomeInput },
    ]
  },
  {
    module: 'src/components/da-loan/ui/income-input',
    exports: [
      { name: 'IncomeInput', value: IncomeInput_24b3169fe3ee539e8d45512dc2dfe583feecac17 },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image_5d8ce56058442d94361877e28c501c951a554a6a },
    ]
  },
  {
    module: 'components/da-loan/blocks/loan-calculator',
    exports: [
      { name: 'LoanCalculator', value: LoanCalculator },
    ]
  },
  {
    module: 'components/da-loan/blocks/consolidation-calculator',
    exports: [
      { name: 'ConsolidationCalculator', value: ConsolidationCalculator },
    ]
  },
  {
    module: '@hookform/resolvers/zod',
    exports: [
      { name: 'zodResolver', value: zodResolver },
    ]
  },
  {
    module: 'components/da-loan/ui-primitive/input',
    exports: [
      { name: 'Input', value: Input_849d1c78d50a3e8698b64091f7b49054601f2a35 },
    ]
  },
  {
    module: 'lib/schemas',
    exports: [
      { name: 'pulseRegistrationSchema', value: pulseRegistrationSchema },
    ]
  },
  {
    module: 'components/da-loan/blocks/loan-products-block',
    exports: [
      { name: 'LoanProductsBlock', value: LoanProductsBlock },
    ]
  },
  {
    module: 'components/da-loan/ui-primitive/sheet',
    exports: [
      { name: 'Sheet', value: Sheet },
      { name: 'SheetContent', value: SheetContent },
      { name: 'SheetHeader', value: SheetHeader },
      { name: 'SheetTitle', value: SheetTitle },
      { name: 'SheetTrigger', value: SheetTrigger },
      { name: 'SheetClose', value: SheetClose },
    ]
  },
  {
    module: 'components/da-loan/ui-primitive/logo',
    exports: [
      { name: 'Logo', value: Logo },
    ]
  },
  {
    module: 'components/da-loan/ui-primitive/dropdown-menu',
    exports: [
      { name: 'DropdownMenu', value: DropdownMenu },
      { name: 'DropdownMenuContent', value: DropdownMenuContent },
      { name: 'DropdownMenuItem', value: DropdownMenuItem },
      { name: 'DropdownMenuTrigger', value: DropdownMenuTrigger },
    ]
  },
  {
    module: 'components/da-loan/blocks/promo-card',
    exports: [
      { name: 'PromoCard', value: PromoCard },
    ]
  },
  {
    module: 'components/da-loan/layout/loan-application-flow-alt/loan-application-flow-alt',
    exports: [
      { name: 'LoanApplicationFlowAlt', value: LoanApplicationFlowAlt },
    ]
  },
  {
    module: 'components/da-loan/ui-primitive/carousel',
    exports: [
      { name: 'Carousel', value: Carousel },
      { name: 'CarouselContent', value: CarouselContent },
      { name: 'CarouselItem', value: CarouselItem },
      { name: 'CarouselPagination', value: CarouselPagination },
    ]
  },
  {
    module: 'embla-carousel-autoplay',
    exports: [
      { name: 'default', value: Autoplay },
    ]
  },
  {
    module: 'components/da-loan/layout/navigation-menu/navigation-menu',
    exports: [
      { name: 'DesktopNavigation', value: DesktopNavigation },
      { name: 'MobileMenuButton', value: MobileMenuButton },
    ]
  },
  {
    module: 'src/components/da-loan/layout/direct-talk/topics-data',
    exports: [
      { name: 'directTalkTopics', value: directTalkTopics },
    ]
  },
  {
    module: 'components/da-loan/blocks/consolidation-benefits',
    exports: [
      { name: 'ConsolidationBenefits', value: ConsolidationBenefits },
    ]
  },
  {
    module: 'components/da-loan/blocks/faq-accordion',
    exports: [
      { name: 'FAQAccordion', value: FAQAccordion },
    ]
  },
  {
    module: 'components/da-loan/blocks/offer-slider',
    exports: [
      { name: 'OfferSlider', value: OfferSlider },
    ]
  },
  {
    module: 'hooks/use-is-in-view',
    exports: [
      { name: 'useIsInView', value: useIsInView },
    ]
  },
  {
    module: 'src/components/da-loan/blocks/slider-component',
    exports: [
      { name: 'LoanSlider', value: LoanSlider },
    ]
  },
  {
    module: 'src/components/da-loan/blocks/loan-summary',
    exports: [
      { name: 'LoanSummary', value: LoanSummary },
    ]
  },
  {
    module: 'src/components/da-loan/blocks/account-selection-form',
    exports: [
      { name: 'AccountSelectionForm', value: AccountSelectionForm },
    ]
  },
  {
    module: 'src/components/da-loan/blocks/consolidation-summary',
    exports: [
      { name: 'ConsolidationSummary', value: ConsolidationSummary },
    ]
  },
  {
    module: 'components/da-loan/ui/select',
    exports: [
      { name: 'Select', value: Select_87560054f54a6d1e822ff059c9b85315bc1265a4 },
      { name: 'SelectContent', value: SelectContent_87560054f54a6d1e822ff059c9b85315bc1265a4 },
      { name: 'SelectItem', value: SelectItem_87560054f54a6d1e822ff059c9b85315bc1265a4 },
      { name: 'SelectTrigger', value: SelectTrigger_87560054f54a6d1e822ff059c9b85315bc1265a4 },
      { name: 'SelectValue', value: SelectValue_87560054f54a6d1e822ff059c9b85315bc1265a4 },
    ]
  },
  {
    module: 'src/lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: '@sitecore-cloudsdk/events/browser',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  }
];

export default combineImportEntries(defaultImportEntries, importMap);
